name: Test

on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1.6.0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.2.3
        with:
          version: 6.17.0
          run_install: true
      - name: Run tests
        run: |
          node tests/basic.js || exit 1
          node tests/advanced.js || exit 1
